In [27]:
import numpy as np
import pandas as pd
import sklearn.model_selection as ms
import sklearn.datasets as ds

In [30]:
data = ds.load_iris()
df = pd.DataFrame(data= np.c_[data['data'], data['target']],
                     columns= data['feature_names'] + ['target'])
df
df.target.replace({0:'setosa',1:'versicolor',2:'virginica'},inplace=True)
df
df.sample(frac=1).reset_index(drop=True)
X = data['data']
y = data['target']
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        target  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [12]:
X_train, X_test, y_train, y_test = ms.train_test_split(X,y,test_size=0.3)

In [9]:
kf = ms.KFold(n_splits=10,shuffle=True,)
X_trains = []
X_tests = []
y_trains = []
y_tests = []
for train_index, test_index in kf.split(X):
    #print("TRAIN:", train_index, "TEST:", test_index)
    
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    X_trains.append(X_train)
    X_tests.append(X_test)
    y_trains.append(y_train)
    y_tests.append(y_test)

In [10]:
from sklearn import tree

In [11]:
clf = tree.DecisionTreeClassifier()

In [13]:
clf.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [15]:
clf.predict(X_test)

array([0, 0, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 0, 1, 2,
       0, 2, 2, 0, 1, 1, 0, 1, 2, 2, 0, 0, 1, 2, 1, 2, 0, 0, 1, 1, 0, 2,
       2])

In [16]:
y_test

array([0, 0, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 0, 1, 2,
       0, 2, 2, 0, 1, 1, 0, 1, 2, 2, 0, 0, 1, 1, 1, 2, 0, 0, 1, 1, 0, 2,
       2])

In [17]:
clf.score(X_test,y_test)

0.9777777777777777

In [25]:
from IPython.display import Image  
from sklearn.externals.six import StringIO  
import pydotplus
dot_data = StringIO() 
tree.export_graphviz(clf,
                     out_file=dot_data,
                     feature_names=data['feature_names'],
                     class_names=data['target_names'],
                     filled=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

InvocationException: GraphViz's executables not found

In [21]:
from sklearn.naive_bayes import GaussianNB

In [22]:
clf2 = GaussianNB()
clf2.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [23]:
clf2.predict_proba(X_test)

array([[1.00000000e+000, 2.85797192e-016, 1.08032562e-028],
       [1.00000000e+000, 9.02254187e-016, 9.14288644e-028],
       [8.71537359e-096, 9.91355410e-001, 8.64458961e-003],
       [4.75035965e-148, 4.71596611e-001, 5.28403389e-001],
       [1.55045932e-244, 2.85508590e-011, 1.00000000e+000],
       [7.93133299e-274, 1.27444550e-011, 1.00000000e+000],
       [1.00000000e+000, 2.17271679e-016, 2.96583767e-028],
       [4.66604221e-184, 4.99210591e-004, 9.99500789e-001],
       [3.21731585e-096, 9.87900772e-001, 1.20992279e-002],
       [1.66240768e-126, 9.49358948e-002, 9.05064105e-001],
       [1.70349053e-212, 1.40239031e-006, 9.99998598e-001],
       [1.46121551e-218, 2.86791871e-006, 9.99997132e-001],
       [4.85719751e-076, 9.99883585e-001, 1.16415239e-004],
       [1.00000000e+000, 9.73862317e-017, 8.08592176e-029],
       [1.36961723e-148, 7.66534346e-003, 9.92334657e-001],
       [2.40868545e-147, 1.26130309e-002, 9.87386969e-001],
       [1.00000000e+000, 1.21536280e-017

In [26]:
import matplotlib.pyplot as plt
%matplotlib inline
def plot_confusion_matrix(cm, labels,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    import itertools
    fig = plt.figure()
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix')

    classes=[None if i%2==0 else labels[int((i-1)/2)] for i in range(2*len(labels)+1)]
    plt.imshow(cm,
           cmap=cmap,
           extent=[0,len(classes)-1,0,len(classes)-1],
           aspect=1)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=90)
    plt.yticks(tick_marks, reversed(classes))

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    cm2 = np.array(list(reversed(cm)))
    for i,j in itertools.product(range(len(classes)), range(len(classes))):
        if i%2==1 and j%2==1:
            plt.text(j,i, format(cm2[int((i-1)/2), int((j-1)/2)], fmt),
                     horizontalalignment="center",verticalalignment="center",
                     color="white" if cm2[int((i-1)/2), int((j-1)/2)] > thresh else "black")
    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    return fig